DROP TABLE IF EXISTS `account_logs`;
CREATE TABLE `account_logs` (
  `log_id` int NOT NULL AUTO_INCREMENT,
  `account_id` int NOT NULL,
  `owner_id` int NOT NULL,
  `action` varchar(50) NOT NULL,
  `source` varchar(50) DEFAULT NULL,
  `transaction_id` int DEFAULT NULL,
  `old_balance` decimal(15,2) DEFAULT NULL,
  `new_balance` decimal(15,2) DEFAULT NULL,
  `old_data` json DEFAULT NULL,
  `new_data` json DEFAULT NULL,
  `changed_fields` json DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  KEY `idx_account` (`account_id`),
  KEY `idx_owner` (`owner_id`),
  KEY `idx_action` (`action`),
  KEY `idx_transaction` (`transaction_id`),
  KEY `idx_created` (`created_at`),
  CONSTRAINT `account_logs_ibfk_1` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`account_id`) ON DELETE CASCADE,
  CONSTRAINT `account_logs_ibfk_2` FOREIGN KEY (`owner_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE,
  CONSTRAINT `account_logs_ibfk_3` FOREIGN KEY (`transaction_id`) REFERENCES `transactions` (`transaction_id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=82 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `accounts`;
CREATE TABLE `accounts` (
  `account_id` int NOT NULL AUTO_INCREMENT,
  `owner_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `account_type` enum('cash','bank','mobile_money','credit','savings','other') NOT NULL,
  `description` text,
  `balance` decimal(15,2) NOT NULL DEFAULT '0.00',
  `opening_balance` decimal(15,2) NOT NULL DEFAULT '0.00',
  `is_global` tinyint(1) NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`account_id`),
  KEY `idx_owner` (`owner_id`),
  KEY `idx_type` (`account_type`),
  KEY `idx_deleted` (`is_deleted`),
  KEY `idx_active` (`is_active`),
  KEY `idx_balance` (`balance`),
  CONSTRAINT `accounts_ibfk_1` FOREIGN KEY (`owner_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `audit_log`;
CREATE TABLE `audit_log` (
  `audit_id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `target_table` varchar(50) NOT NULL,
  `target_id` int NOT NULL,
  `action` varchar(50) NOT NULL,
  `changed_fields` json DEFAULT NULL,
  `old_values` json DEFAULT NULL,
  `new_values` json DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `is_global` tinyint(1) NOT NULL DEFAULT '0',
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`audit_id`),
  KEY `idx_target` (`target_table`,`target_id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_timestamp` (`timestamp`),
  KEY `idx_action` (`action`),
  CONSTRAINT `audit_log_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `category_id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `parent_id` int DEFAULT NULL,
  `is_global` tinyint(1) NOT NULL DEFAULT '0',
  `owner_id` int NOT NULL,
  `updated_by` int NOT NULL,
  `description` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`category_id`),
  UNIQUE KEY `unique_name_per_parent` (`parent_id`,`name`,`is_deleted`),
  KEY `updated_by` (`updated_by`),
  KEY `idx_parent` (`parent_id`),
  KEY `idx_owner` (`owner_id`),
  KEY `idx_deleted` (`is_deleted`),
  CONSTRAINT `categories_ibfk_1` FOREIGN KEY (`parent_id`) REFERENCES `categories` (`category_id`) ON DELETE SET NULL,
  CONSTRAINT `categories_ibfk_2` FOREIGN KEY (`owner_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE,
  CONSTRAINT `categories_ibfk_3` FOREIGN KEY (`updated_by`) REFERENCES `users` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `recurring_logs`;
CREATE TABLE `recurring_logs` (
  `log_id` int NOT NULL AUTO_INCREMENT,
  `owner_id` int NOT NULL,
  `recurring_id` int NOT NULL,
  `run_date` datetime NOT NULL,
  `amount_used` decimal(15,2) NOT NULL,
  `status` enum('generated','skipped','failed') NOT NULL,
  `override_used` tinyint(1) NOT NULL DEFAULT '0',
  `posted_transaction_id` int DEFAULT NULL,
  `message` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  KEY `idx_owner` (`owner_id`),
  KEY `idx_recurring` (`recurring_id`),
  KEY `idx_run_date` (`run_date`),
  KEY `idx_status` (`status`),
  KEY `idx_transaction` (`posted_transaction_id`),
  KEY `idx_recurring_date` (`recurring_id`,`run_date`),
  CONSTRAINT `recurring_logs_ibfk_1` FOREIGN KEY (`owner_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE,
  CONSTRAINT `recurring_logs_ibfk_2` FOREIGN KEY (`recurring_id`) REFERENCES `recurring_transactions` (`recurring_id`) ON DELETE CASCADE,
  CONSTRAINT `recurring_logs_ibfk_3` FOREIGN KEY (`posted_transaction_id`) REFERENCES `transactions` (`transaction_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `recurring_transactions`;
CREATE TABLE `recurring_transactions` (
  `recurring_id` int NOT NULL AUTO_INCREMENT,
  `owner_id` int NOT NULL,
  `is_global` tinyint(1) NOT NULL DEFAULT '0',
  `name` varchar(255) NOT NULL,
  `description` text,
  `frequency` enum('daily','weekly','monthly','yearly') NOT NULL DEFAULT 'monthly',
  `interval_value` int NOT NULL DEFAULT '1',
  `next_due` datetime NOT NULL,
  `last_run` datetime DEFAULT NULL,
  `max_missed_runs` int NOT NULL DEFAULT '12',
  `last_run_status` enum('success','failed','skipped') NOT NULL DEFAULT 'success',
  `pause_until` datetime DEFAULT NULL,
  `skip_next` tinyint(1) NOT NULL DEFAULT '0',
  `override_amount` decimal(15,2) DEFAULT NULL,
  `amount` decimal(15,2) NOT NULL,
  `category_id` int DEFAULT NULL,
  `transaction_type` enum('income','expense','transfer','debts') NOT NULL DEFAULT 'expense',
  `payment_method` enum('cash','bank','mobile_money','credit','other') NOT NULL DEFAULT 'mobile_money',
  `notes` text,
  `account_id` int DEFAULT NULL,
  `source_account_id` int DEFAULT NULL,
  `destination_account_id` int DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`recurring_id`),
  KEY `idx_owner` (`owner_id`),
  KEY `idx_next_due` (`next_due`),
  KEY `idx_active` (`is_active`),
  KEY `idx_deleted` (`is_deleted`),
  KEY `idx_frequency` (`frequency`),
  KEY `idx_category` (`category_id`),
  KEY `idx_account` (`account_id`),
  KEY `idx_source` (`source_account_id`),
  KEY `idx_destination` (`destination_account_id`),
  KEY `idx_due_active` (`next_due`,`is_active`,`is_deleted`),
  CONSTRAINT `recurring_transactions_ibfk_1` FOREIGN KEY (`owner_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE,
  CONSTRAINT `recurring_transactions_ibfk_2` FOREIGN KEY (`category_id`) REFERENCES `categories` (`category_id`) ON DELETE SET NULL,
  CONSTRAINT `recurring_transactions_ibfk_3` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`account_id`) ON DELETE RESTRICT,
  CONSTRAINT `recurring_transactions_ibfk_4` FOREIGN KEY (`source_account_id`) REFERENCES `accounts` (`account_id`) ON DELETE RESTRICT,
  CONSTRAINT `recurring_transactions_ibfk_5` FOREIGN KEY (`destination_account_id`) REFERENCES `accounts` (`account_id`) ON DELETE RESTRICT,
  CONSTRAINT `recurring_transactions_chk_1` CHECK ((((`transaction_type` in (_cp850'income',_cp850'expense',_cp850'debts')) and (`account_id` is not null) and (`source_account_id` is null) and (`destination_account_id` is null)) or ((`transaction_type` = _cp850'transfer') and (`account_id` is null) and (`source_account_id` is not null) and (`destination_account_id` is not null) and (`source_account_id` <> `destination_account_id`)))),
  CONSTRAINT `recurring_transactions_chk_2` CHECK ((`amount` > 0)),
  CONSTRAINT `recurring_transactions_chk_3` CHECK ((`interval_value` > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `transactions`;
CREATE TABLE `transactions` (
  `transaction_id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `title` varchar(255) NOT NULL,
  `transaction_type` enum('income','expense','transfer','debt','investment') NOT NULL,
  `amount` decimal(15,2) NOT NULL,
  `payment_method` enum('cash','bank','mobile_money','credit_card','other') NOT NULL,
  `account_id` int DEFAULT NULL,
  `source_account_id` int DEFAULT NULL,
  `destination_account_id` int DEFAULT NULL,
  `parent_transaction_id` int DEFAULT NULL,
  `category_id` int DEFAULT NULL,
  `description` text,
  `transaction_date` date NOT NULL,
  `is_global` tinyint(1) NOT NULL DEFAULT '0',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`transaction_id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_account` (`account_id`),
  KEY `idx_source` (`source_account_id`),
  KEY `idx_destination` (`destination_account_id`),
  KEY `idx_category` (`category_id`),
  KEY `idx_type` (`transaction_type`),
  KEY `idx_date` (`transaction_date`),
  KEY `idx_deleted` (`is_deleted`),
  KEY `idx_user_date` (`user_id`,`transaction_date`),
  KEY `fk_parent_transaction` (`parent_transaction_id`),
  CONSTRAINT `fk_parent_transaction` FOREIGN KEY (`parent_transaction_id`) REFERENCES `transactions` (`transaction_id`) ON DELETE SET NULL,
  CONSTRAINT `transactions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE,
  CONSTRAINT `transactions_ibfk_2` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`account_id`) ON DELETE RESTRICT,
  CONSTRAINT `transactions_ibfk_3` FOREIGN KEY (`source_account_id`) REFERENCES `accounts` (`account_id`) ON DELETE RESTRICT,
  CONSTRAINT `transactions_ibfk_4` FOREIGN KEY (`destination_account_id`) REFERENCES `accounts` (`account_id`) ON DELETE RESTRICT,
  CONSTRAINT `transactions_ibfk_5` FOREIGN KEY (`category_id`) REFERENCES `categories` (`category_id`) ON DELETE SET NULL,
  CONSTRAINT `transactions_chk_1` CHECK ((((`transaction_type` in (_cp850'income',_cp850'expense',_cp850'debt_repaid',_cp850'debt_borrowed')) and (`account_id` is not null) and (`source_account_id` is null) and (`destination_account_id` is null)) or ((`transaction_type` in (_cp850'transfer',_cp850'investment_deposit',_cp850'investment_withdraw')) and (`account_id` is null) and (`source_account_id` is not null) and (`destination_account_id` is not null)))),
  CONSTRAINT `transactions_chk_2` CHECK ((`amount` > 0))
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `user_id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `security_question` varchar(255) DEFAULT 'What is your Favourite colour',
  `security_answer_hash` varchar(255) NOT NULL,
  `role` enum('admin','user') NOT NULL DEFAULT 'user',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

